name: brainlab
channels:
  - conda
  - pip
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - numba
  - pip
  - matplotlib
  - seaborn
  - pip:
      - tvb-library
      - jsonpickle

